package com.tunjid.snapshottable.compat

/**
 * Translates the version string reported by `META-INF/compiler.version` into the version that
 * actually describes the API surface of the hosting compiler.
 *
 * IntelliJ IDEA, Android Studio, and Kotlin dev/EAP builds frequently advertise version strings
 * that do not correspond to any released Kotlin tag. For example, IntelliJ 2025.3.x ships a
 * Kotlin compiler that reports `2.3.20-ij253-87` but is actually built from a `2.3.0-dev-9992`
 * snapshot, predating the `FirSimpleFunction → FirNamedFunction` rename. Without translation,
 * factory selection routes to the `k2320` impl whose bytecode references `FirNamedFunction`,
 * and the IDE crashes with `NoSuchMethodError`.
 *
 * The built-in table lives in [BUILT_IN_COMPILER_VERSION_ALIASES] (generated by the
 * `:compiler-compat` BuildConfig from `ide-mappings.txt`). Callers may overlay project-specific
 * aliases via the `userAliases` parameter.
 */
public object CompilerVersionAliases {
    /**
     * Sentinel mapping value indicating "this IDE build has no working compat path — bail
     * gracefully instead of registering FIR extensions that will crash". When [map] sees this
     * value it returns `null`.
     */
    public const val CLI_ONLY: String = "CLI_ONLY"

    /**
     * Resolves [version] through user-supplied and built-in alias tables.
     *
     * - User aliases win over built-in aliases.
     * - If no alias matches, [version] is returned unchanged.
     * - If the matched alias is [CLI_ONLY], returns `null` to signal that the caller should
     *   skip registering compat-dependent extensions.
     */
    public fun map(
        version: KotlinToolingVersion,
        userAliases: Map<String, String> = emptyMap(),
    ): KotlinToolingVersion? {
        val key = version.toString()
        val alias = userAliases[key] ?: BUILT_IN_COMPILER_VERSION_ALIASES[key]
        return when (alias) {
            null -> version
            CLI_ONLY -> null
            else -> KotlinToolingVersion(alias)
        }
    }
}
